logging:
  level[net.talaatharb.patientmanagementsystem]: DEBUG

spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:file:../db/patient-management-system;AUTO_SERVER=TRUE;
    username: sa
    password: