server:
  port: 8080
  shutdown: graceful
  
logging:
  level[net.talaatharb.patientmanagementsystem]: DEBUG
  level[org.springframework.web]: DEBUG

spring:
  jpa:
    open-in-view: false
    database: default
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:../db/patient-management-system;AUTO_SERVER=TRUE;
    username: sa
    password: