name: Deploy to heroku

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "patient-management-system-demo" #Must be unique in Heroku
          heroku_email: "eng.talat.harb@gmail.com"
          usedocker: true
          healthcheck: "https://patient-management-system-demo.herokuapp.com/actuator/health"
          delay: 90